name: Nightly Ticket Summary

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'  # 05:00 UTC = 01:00 America/New_York

jobs:
  nightly-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Fetch Yesterday's report
        run: node scripts/fetchAndPush.js "Yesterday"
        env:
          DISTRIBUTE_USER: ${{ secrets.DISTRIBUTE_USER }}
          DISTRIBUTE_PASS: ${{ secrets.DISTRIBUTE_PASS }}
          SHEET_ID:          ${{ secrets.SHEET_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: service-account.json
          # You’ll also need to add GCP_SA_KEY secret and authenticate
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build Summary Pivot
        run: node scripts/buildSummary.js
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: service-account.json
